version: '3.8'
services:
  db:
    container_name: local_database
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: local_password
      MARIADB_DATABASE: local_db
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql